import numpy as np
import pandas as pd



def obs_times_to_store(T):
    """
    Returns an array of 10 observation times and preprends time 1, giving a total of
    11 times.
    """
    Ts_to_store_excl_1 = np.linspace(T // 10, T, num=10, dtype=np.int64)
    arr_1 = np.array([1], dtype=np.int64)
    obs_times_to_store = np.concatenate([arr_1] + [Ts_to_store_excl_1], axis=0)
    obs_times_to_store = obs_times_to_store - 1 # subtract 1 from all times
    return obs_times_to_store

def kalman_results_to_df(kalman):
    """
    Converts the output of the RTS smoother to a pd.DataFrame, containing the true value quantities 
    of interest for the experiment.
    """
    T = len(kalman.data)
    results_df_dict = {}
    obs_times = obs_times_to_store(T)
    results_df_dict['T'] = obs_times.tolist()
    filt = kalman.filt; smth = kalman.smth
    dimX = kalman.filt[0].mean.ravel().shape[0]
    for d in range(dimX):
        results_df_dict[f'x_t_filt_mean_{d+1}'] = [filt[t].mean.ravel()[d] for t in obs_times]
        results_df_dict[f'x_t_filt_std_{d+1}'] = [np.sqrt(np.diag(filt[t].cov))[d] for t in obs_times]
        results_df_dict[f'x_t_smth_mean_{d+1}'] = [smth[t].mean.ravel()[d] for t in obs_times]
        results_df_dict[f'x_t_smth_std_{d+1}'] = [np.sqrt(np.diag(smth[t].cov))[d] for t in obs_times]
    results_df = pd.DataFrame(results_df_dict)
    results_df.set_index('T', inplace=True)
    return results_df

def benchmark_pf_results_to_df(filt, smth):
    """
    Inputs
    ---------
    filt: List of moments objects. 
        Each moment object is a dict that contains `mean` and `var` keys.
        These keys contain either (dimX, ) arrays in the mv case, or floats in the univ case.
    smth: dict containing the keys 'phi_x' and 'phi_x_x' containing (T, ) or (T, dimX) arrays  

    Returns
    ---------
    results_df: pd.DataFrame
    """
    T = len(filt)
    results_df_dict = {}
    obs_times = obs_times_to_store(T)
    results_df_dict['T'] = obs_times.tolist()
    univ = isinstance(filt[0]['mean'], float)
    dimX = 1 if univ else filt[0]['mean'].shape[0]
    for d in range(dimX):
        if univ:
            results_df_dict[f'x_t_filt_mean_{d+1}_pf'] = [filt[t]['mean'] for t in obs_times]
            results_df_dict[f'x_t_filt_std_{d+1}_pf'] = [np.sqrt(filt[t]['var']) for t in obs_times]
            results_df_dict[f'x_t_smth_mean_{d+1}_pf'] = [smth['phi_x'][t] for t in obs_times]
            results_df_dict[f'x_t_smth_std_{d+1}_pf'] = [np.sqrt(smth['phi_x_x'][t] - (smth['phi_x'][t] ** 2)) for t in obs_times]
        else:
            results_df_dict[f'x_t_filt_mean_{d+1}_pf'] = [filt[t]['mean'][d] for t in obs_times]
            results_df_dict[f'x_t_filt_std_{d+1}_pf'] = [np.sqrt(filt[t]['var'][d]) for t in obs_times]
            results_df_dict[f'x_t_smth_mean_{d+1}_pf'] = [smth['phi_x'][t][d] for t in obs_times]
            results_df_dict[f'x_t_smth_std_{d+1}_pf'] = [np.sqrt(smth['phi_x_x'][t][d] - (smth['phi_x'][t][d] ** 2)) for t in obs_times]
    results_df = pd.DataFrame(results_df_dict)
    results_df.set_index('T', inplace=True)
    return results_df
    
def multismooth_results_to_df(results):
    """
    Converts the output of the multiplexer + smoothing_worker algorithm to a pd.DataFrame, 
    containing the quantities of interest for the experiment.
    
    At each of the times generated by the `obs_times_to_store` function above, and 
    across each dimension of the latent SDE, the estimators of the first moment E[X_t] 
    and the second moment: E[X_t^2] are stored.
    """
    results_df_dict = {} 
    results_df_dict['run_id'] = [r['run'] for r in results]
    results_df_dict['seed'] = [r['seed'] for r in results]
    results_df_dict['method'] = [r['method'] for r in results]
    results_df_dict['fk'] = [r['fk'] for r in results]
    results_df_dict['cpu'] = [r['cpu_time'] for r in results]
    T = results[0]['phi_x'].shape[0]
    example_mean = results[0]['phi_x'][0]
    quantile_index = results[0]['quantile_index']
    obs_times = obs_times_to_store(T)
    if isinstance(example_mean, float):
        for t in obs_times:
            results_df_dict[f'x_{t}_est_1'] = [r['phi_x'][t] for r in results]
            results_df_dict[f'x_{t}_sq_est_1'] = [r['phi_x_x'][t] for r in results]
            for k, q in enumerate(quantile_index):
                q_str = str(round(q, 2))
                results_df_dict[f'x_{t}_q{q_str}_est_1'] = [r['quantiles'][k][t] for r in results]
    else:
        for i in range(len(example_mean)): # Iterate over dimension
            for t in obs_times: # Iterate over obs times
                results_df_dict[f'x_{t}_est_{i+1}'] = [r['phi_x'][t][i] for r in results]
                results_df_dict[f'x_{t}_sq_est_{i+1}'] = [r['phi_x_x'][t][i] for r in results]
                for k, q in enumerate(quantile_index): # Iterate over quantile index
                    q_str = str(round(q, 2))
                    results_df_dict[f'x_{t}_q{q_str}_est_{i+1}'] = [r['quantiles'][k][0][i] for r in results]
    return pd.DataFrame(results_df_dict)
